version: "3.9"
services:
  web:
    image: nicolasquiceno/acm-argo-app:0.0.5
    platform: linux/amd64
    build: .
    ports:
      - "8080:8080"
    environment:
      TITLE: acm-argo-app
      DESCRIPTION: Test
      HOST: "0.0.0.0"
      PORT: 8080
