apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: Placement
metadata:
  name: acm-argocd-app-placement
  namespace: openshift-gitops
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchLabels:
          cluster-app: true
