apiVersion: v1
kind: Service
metadata:
  name: acm-argo-app-port
spec:
  selector:
    app: acm-argo-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30585
  type: NodePort